##### This file let's you calculates the quantitative metrics for any pooling method and seed.

In [1]:
# Imports
import pandas as pd
import numpy as np
import os
import sys
import pickle
import torch
from collections import defaultdict
from scipy.stats import spearmanr
import shap
import json

In [2]:
# Add project root to path to find models.py
project_root = os.path.abspath(os.path.join(os.path.dirname(__file__), '..')) \
    if '__file__' in globals() else os.path.abspath("..")

if project_root not in sys.path:
    sys.path.insert(0, project_root)

from models import PolicyNetwork, create_mil_model_with_dict

In [3]:
# Main Configuration
SEED_TO_ANALYZE = 8
POOLING_METHOD_TO_ANALYZE = "repset"
TOP_K_FOR_COUNTS = 20
REPRODUCIBILITY_SEED = 42
DEMOGRAPHIC_LABELS = ['Imd Band', 'Region', 'Gender', 'Age Band', 'Disability']

OUTPUT_DIR = '../results/'


# These depend on which specific experiments you did
DATASET_CONFIGS = {
    "oulad_full": {
        "base_path": f'/projects/prjs1491/Attention-based-RL-MIL/runs/classification/seed_{SEED_TO_ANALYZE}/oulad_full/instances/tabular/label/bag_size_20/{POOLING_METHOD_TO_ANALYZE}_20_16_20',
        "raw_data_path": '/projects/prjs1491/Attention-based-RL-MIL/data/oulad/oulad_full_raw.pkl',
        "output_dir": OUTPUT_DIR,
        "models": {
            "Linear Attention": {
                "run_dir_suffix": 'neg_policy_only_loss_attention_linear_reg_sum_sample_without_replacement/',
                "output_file": "attention_linear_outputs.csv",
                "score_column": "attention_score"
            },
            "Gated Attention": {
                "run_dir_suffix": 'neg_policy_only_loss_attention_gated_reg_sum_sample_without_replacement/',
                "output_file": "attention_gated_outputs.csv",
                "score_column": "attention_score"
            },
            "Multi-Head Attention": {
                "run_dir_suffix": 'neg_policy_only_loss_attention_multi_head_reg_sum_sample_without_replacement/',
                "output_file": "attention_multi_head_outputs.csv",
                "score_column": "attention_score"
            },
            "Epsilon-Greedy (SHAP)": {
                "is_shap_model": True,
                "score_column": "shap_value",
                # Which model's weights to load for the explanation
                "model_to_explain_suffix": 'neg_policy_only_loss_epsilon_greedy_reg_sum_sample_without_replacement/',
                # Which model's output file to use for the instance features
                "feature_source_file": "attention_gated_outputs.csv",
                "feature_source_suffix": 'neg_policy_only_loss_attention_gated_reg_sum_sample_without_replacement/'
            }
        }
    },
    "oulad_aggregated": {
        "base_path": f'/projects/prjs1491/Attention-based-RL-MIL/runs/classification/seed_{SEED_TO_ANALYZE}/oulad_aggregated/instances/tabular/label/bag_size_20/{POOLING_METHOD_TO_ANALYZE}_22_16_22/',
        "raw_data_path": '/projects/prjs1491/Attention-based-RL-MIL/data/oulad/oulad_aggregated_raw.pkl',
        "output_dir": OUTPUT_DIR,
        "models": {
            "Linear Attention": {
                "run_dir_suffix": 'neg_policy_only_loss_attention_linear_reg_sum_sample_without_replacement/',
                "output_file": "attention_linear_outputs.csv",
                "score_column": "attention_score"
            },
            "Gated Attention": {
                "run_dir_suffix": 'neg_policy_only_loss_attention_gated_reg_sum_sample_without_replacement/',
                "output_file": "attention_gated_outputs.csv",
                "score_column": "attention_score"
            },
            "Multi-Head Attention": {
                "run_dir_suffix": 'neg_policy_only_loss_attention_multi_head_reg_sum_sample_without_replacement/',
                "output_file": "attention_multi_head_outputs.csv",
                "score_column": "attention_score"
            },
            "Epsilon-Greedy (SHAP)": {
                "is_shap_model": True,
                "score_column": "shap_value",
                "model_to_explain_suffix": 'neg_policy_only_loss_epsilon_greedy_reg_sum_sample_without_replacement/',
                "feature_source_file": "attention_gated_outputs.csv",
                "feature_source_suffix": 'neg_policy_only_loss_attention_gated_reg_sum_sample_without_replacement/'
            }
        }
    }
}

for config in DATASET_CONFIGS.values():
    os.makedirs(config['output_dir'], exist_ok=True)

In [4]:
# Helper functions
def generate_general_labels(raw_bag_data):
    labels = []
    for instance_list in raw_bag_data:
        main_tuple = instance_list[0]
        if main_tuple[0] == 'assessment_type':
            labels.append(f"Assessment: {main_tuple[1]}")
        elif main_tuple[0] == 'activity_type':
            labels.append(f"VLE Clicks: {main_tuple[1]}")
        else:
            labels.append(main_tuple[0].replace('_', ' ').title())
    return labels

def build_bag_to_labels_map(raw_data_path):
    print("\nBuilding global map from Bag ID to Instance Labels")
    try:
        with open(raw_data_path, 'rb') as f:
            data = pickle.load(f)
    except FileNotFoundError:
        print(f"FATAL: Raw data file not found at {raw_data_path}")
        return {}

    # Debug check
    if not all(k in data for k in ("bag_ids", "raw_bags")):
        print(f"Unexpected pickle format. Keys found: {list(data.keys())}")
        return {}

    bag_to_labels = {}
    for bag_id, raw_bag in zip(data['bag_ids'], data['raw_bags']):
        bag_to_labels[str(bag_id)] = generate_general_labels(raw_bag)

    print(f"Built map for {len(bag_to_labels)} bags.")
    return bag_to_labels


def print_counts_table(model_name, counts_dict, bag_presence_dict, total_bags):
    print(f"\n--- Top-{TOP_K_FOR_COUNTS} Feature Counts for: {model_name.upper()} ---")
    if not counts_dict:
        print("No instances were found in the top 20.")
        return

    df = pd.DataFrame(counts_dict.items(), columns=['Feature Type', 'Total Count in Top-20'])
    df['Present in X Bags'] = df['Feature Type'].map(bag_presence_dict)
    df['Bag Presence %'] = df['Present in X Bags'] / total_bags * 100
    df['Avg Count When Present'] = df['Total Count in Top-20'] / df['Present in X Bags']
    df = df.sort_values(by='Total Count in Top-20', ascending=False).reset_index(drop=True)
    print(f"Based on {total_bags} common bags.")
    display(df)


def calculate_hhi(counts_dict, total_bags):
    total_top_k_instances = total_bags * TOP_K_FOR_COUNTS
    if total_top_k_instances == 0: return 0
    frequencies = np.array(list(counts_dict.values())) / total_top_k_instances
    return np.sum(frequencies**2)


def calculate_gini(counts_dict):
    counts = np.array(list(counts_dict.values()), dtype=np.float64)
    if np.sum(counts) == 0: return 0
    sorted_counts = np.sort(counts)
    n = len(counts)
    cum_counts = np.cumsum(sorted_counts)
    return (n + 1 - 2 * np.sum(cum_counts) / cum_counts[-1]) / n


def get_counts_for_split(bags_list, df_source, score_column, bag_to_labels_map):
    counts = defaultdict(int)
    for bag_id in bags_list:
        if bag_id not in bag_to_labels_map: continue
        bag_labels = bag_to_labels_map[bag_id]
        bag_df = df_source[df_source['bag_id'] == bag_id].reset_index(drop=True)
        if len(bag_labels) != len(bag_df): continue
        top_indices = bag_df.nlargest(TOP_K_FOR_COUNTS, score_column).index
        for idx in top_indices:
            counts[bag_labels[idx]] += 1
    return counts

def load_rl_model(run_dir_path):
    print("Attempting to load RL model...")
    device = torch.device("cpu")
    model_weights_path = os.path.join(run_dir_path, 'sweep_best_model.pt')
    rl_config_path = os.path.join(run_dir_path, 'sweep_best_model_config.json')
    mil_config_path = os.path.join(run_dir_path, '..', 'best_model_config.json')
    mil_weights_path = os.path.join(run_dir_path, '..', 'best_model.pt')
    
    try:
        with open(mil_config_path) as f: mil_config = json.load(f)
        with open(rl_config_path) as f: rl_config = json.load(f)
    except FileNotFoundError as e:
        print(f"FATAL: A config file was not found: {e}"); return None

    task_model = create_mil_model_with_dict(mil_config)
    task_model.load_state_dict(torch.load(mil_weights_path, map_location=device))
    
    policy_network = PolicyNetwork(
        task_model=task_model, state_dim=rl_config['state_dim'], hdim=rl_config['hdim'],
        learning_rate=rl_config['learning_rate'], device=device, task_type=rl_config['task_type'],
        min_clip=rl_config.get('min_clip'), max_clip=rl_config.get('max_clip'),
        sample_algorithm=rl_config.get('sample_algorithm'), no_autoencoder=rl_config.get('no_autoencoder_for_rl', False)
    )
    policy_network.load_state_dict(torch.load(model_weights_path, map_location=device))
    policy_network.eval()
    print("RL model loaded successfully.")
    return policy_network

def parse_feature_string(s):
    if not isinstance(s, str): return np.array([])
    return np.fromstring(s.replace('[','').replace(']','').replace('\n',' '), sep=' ')

def append_to_csv(df, filepath):
    file_exists = os.path.exists(filepath)
    df.to_csv(filepath, mode='a', header=(not file_exists), index=False)
    
    if not file_exists:
        print(f"Created new file and saved results to: {filepath}")
    else:
        print(f"Appended new results to: {filepath}")

In [5]:
# Step 1: Load Bag-to-Label Maps

bag_to_labels_maps = {}

for dataset_name, dataset_config in DATASET_CONFIGS.items():
    print(f"--- Loading label map for: {dataset_name.upper()} ---")
    try:
        bag_to_labels_maps[dataset_name] = build_bag_to_labels_map(dataset_config['raw_data_path'])
        print(f"Successfully loaded map with {len(bag_to_labels_maps[dataset_name])} bags.")
    except Exception as e:
        print(f"    ERROR: Could not load map for {dataset_name}. Error: {e}")

--- Loading label map for: OULAD_FULL ---

Building global map from Bag ID to Instance Labels
Built map for 27379 bags.
Successfully loaded map with 27379 bags.
--- Loading label map for: OULAD_AGGREGATED ---

Building global map from Bag ID to Instance Labels
Built map for 27379 bags.
Successfully loaded map with 27379 bags.

In [6]:
# Step 2: Calculate or Load SHAP Values

all_dfs = {} 

print("Starting SHAP Analysis")

for dataset_name, dataset_config in DATASET_CONFIGS.items():
    for model_name, model_config in dataset_config['models'].items():
        
        # Process only if the model is explicitly marked for SHAP analysis
        if model_config.get("is_shap_model"):
            full_model_name = f"{model_name} on {dataset_name}"
            print(f"\n- Processing SHAP for: {full_model_name}")
            
            shap_filename = f"shap_scores_{dataset_name}_{POOLING_METHOD_TO_ANALYZE}_seed_{SEED_TO_ANALYZE}.csv"
            shap_output_file = os.path.join(dataset_config['output_dir'], shap_filename)
            
            try:
                feature_path = os.path.join(dataset_config['base_path'], model_config['feature_source_suffix'], model_config['feature_source_file'])
                source_df = pd.read_csv(feature_path)
                source_df = source_df[source_df['is_padding_instance'] == False]

                if os.path.exists(shap_output_file):
                    print(f"  Found pre-computed file. Loading from: {shap_output_file}")
                    shap_df_loaded = pd.read_csv(shap_output_file, index_col=0)
                    df = source_df.join(shap_df_loaded)
                else:
                    # SHAP CALCULATION LOGIC
                    print(f"  No SHAP file found at {shap_output_file}.")
                    print("  Starting new calculation (this may take a while)...")
                    
                    model_dir = os.path.join(dataset_config['base_path'], model_config['model_to_explain_suffix'])
                    greedy_model = load_rl_model(model_dir) # Assumes load_rl_model is defined
                    
                    if not greedy_model:
                        print(f"  ERROR: Could not load model from {model_dir}. Skipping.")
                        continue

                    instance_features = np.vstack(source_df['original_instance_content'].apply(parse_feature_string))
                    
                    def shap_wrapper_f(x):
                        with torch.no_grad():
                            return greedy_model(torch.from_numpy(x).float().to("cpu"))[0].cpu().numpy()
                    
                    explainer = shap.KernelExplainer(shap_wrapper_f, shap.sample(instance_features, 50))
                    shap_values = explainer.shap_values(instance_features)
                    
                    shap_df = pd.DataFrame({'shap_value': np.abs(shap_values).mean(axis=1)}, index=source_df.index)
                    
                    print(f"  SHAP values calculated. Saving to: {shap_output_file}")
                    shap_df.to_csv(shap_output_file)
                    
                    df = source_df.join(shap_df)

                all_dfs[full_model_name] = df

            except (FileNotFoundError, KeyError) as e:
                print(f"  WARNING: Could not process {full_model_name}. Error: {e}")

print("\n SHAP analysis complete.")

--- Starting SHAP Analysis ---

- Processing SHAP for: Epsilon-Greedy (SHAP) on oulad_full
  Found pre-computed file. Loading from: ../results/shap_scores_oulad_full_repset_seed_8.csv

- Processing SHAP for: Epsilon-Greedy (SHAP) on oulad_aggregated
  Found pre-computed file. Loading from: ../results/shap_scores_oulad_aggregated_repset_seed_8.csv

--- SHAP analysis complete. ---

In [7]:
# Step 3: Load Standard Model Data

print("Loading standard model data")

for dataset_name, dataset_config in DATASET_CONFIGS.items():
    for model_name, model_config in dataset_config['models'].items():
        
        if not model_config.get("is_shap_model"):
            full_model_name = f"{model_name} on {dataset_name}"
            print(f"Loading: {full_model_name}")
            
            try:
                model_path = os.path.join(dataset_config['base_path'], model_config['run_dir_suffix'], model_config['output_file'])
                df = pd.read_csv(model_path)
                df = df[df['is_padding_instance'] == False]
                
                all_dfs[full_model_name] = df
            except (FileNotFoundError, KeyError) as e:
                print(f"  WARNING: Could not process {full_model_name}. Error: {e}")

--- Loading standard model data ---
Loading: Linear Attention on oulad_full
Loading: Gated Attention on oulad_full
Loading: Multi-Head Attention on oulad_full
Loading: Linear Attention on oulad_aggregated
Loading: Gated Attention on oulad_aggregated
Loading: Multi-Head Attention on oulad_aggregated

--- Standard model loading complete. ---

In [8]:
# Step 4: Find Common Bags Per Dataset

common_bags_per_dataset = {}
dfs_by_dataset = {dataset_name: {} for dataset_name in DATASET_CONFIGS.keys()}

for model_name, df in all_dfs.items():
    for dataset_name in DATASET_CONFIGS.keys():
        if dataset_name in model_name:
            dfs_by_dataset[dataset_name][model_name] = df
            break

for dataset_name, model_dfs in dfs_by_dataset.items():
    if not model_dfs:
        print(f"No models loaded for dataset '{dataset_name}'. Skipping.")
        continue

    common_bags = set.intersection(*(set(df['bag_id'].unique()) for df in model_dfs.values()))
    common_bags_per_dataset[dataset_name] = sorted(list(common_bags))
    print(f"Found {len(common_bags_per_dataset[dataset_name])} common bags for the {len(model_dfs)} models in '{dataset_name}'.")

--- Finding common bags for each dataset ---
- Found 2738 common bags for the 4 models in 'oulad_full'.
- Found 2738 common bags for the 4 models in 'oulad_aggregated'.

In [9]:
# Step 5: Generate Top-20 Counts

all_counts = {name: defaultdict(int) for name in all_dfs.keys()}
all_bag_presence = {name: defaultdict(int) for name in all_dfs.keys()}

for model_name, df_source in all_dfs.items():
    print(f"Processing: {model_name}")
    
    dataset_name = "oulad_full" if "oulad_full" in model_name else "oulad_aggregated"
    correct_map = bag_to_labels_maps[dataset_name]
    common_bags_for_model = common_bags_per_dataset[dataset_name]
    
    base_model_name = model_name.replace(f" on {dataset_name}", "")
    score_col = DATASET_CONFIGS[dataset_name]['models'][base_model_name]['score_column']

    grouped_df = df_source.groupby('bag_id')

    for bag_id in common_bags_for_model:
        if bag_id not in correct_map:
            continue
        
        try:
            bag_df = grouped_df.get_group(bag_id)
            bag_labels = correct_map[bag_id]

            if len(bag_labels) == len(bag_df):
                unique_labels_in_top20 = set()
                top_20 = bag_df.nlargest(TOP_K_FOR_COUNTS, score_col)
                
                for idx in top_20.index:
                    label = bag_labels[bag_df.index.get_loc(idx)]
                    all_counts[model_name][label] += 1
                    unique_labels_in_top20.add(label)
                    
                for label in unique_labels_in_top20:
                    all_bag_presence[model_name][label] += 1
        except KeyError:
            continue

--- Generating Top-20 counts ---
- Processing: Epsilon-Greedy (SHAP) on oulad_full

- Processing: Epsilon-Greedy (SHAP) on oulad_aggregated
- Processing: Linear Attention on oulad_full
- Processing: Gated Attention on oulad_full
- Processing: Multi-Head Attention on oulad_full
- Processing: Linear Attention on oulad_aggregated
- Processing: Gated Attention on oulad_aggregated
- Processing: Multi-Head Attention on oulad_aggregated

--- Count generation complete. ---

In [10]:
# Step 6: Print Descriptive Statistics

for model_name in all_dfs.keys():
    
    if "oulad_full" in model_name:
        dataset_name = "oulad_full"
    elif "oulad_aggregated" in model_name:
        dataset_name = "oulad_aggregated"
    else:
        continue

    total_bags_for_dataset = len(common_bags_per_dataset[dataset_name])
    
    print_counts_table(
        model_name, 
        all_counts[model_name], 
        all_bag_presence[model_name], 
        total_bags_for_dataset
    )

--- Top-20 Feature Counts for: EPSILON-GREEDY (SHAP) ON OULAD_FULL ---
Based on 2738 common bags.

,Feature Type,Total Count in Top-20,Present in X Bags,Bag Presence %,Avg Count When Present
0,VLE Clicks: homepage,11780,2506,91.526662,4.700718
1,VLE Clicks: subpage,5521,1994,72.826881,2.768806
2,Assessment: TMA,4679,1909,69.722425,2.451021
3,VLE Clicks: forumng,4667,1641,59.934259,2.843998
4,VLE Clicks: oucontent,3759,1427,52.118335,2.634198
5,Assessment: CMA,3446,1191,43.498904,2.893367
6,VLE Clicks: resource,3031,1593,58.181154,1.902699
7,VLE Clicks: quiz,1508,869,31.738495,1.735328
8,VLE Clicks: url,1486,811,29.620161,1.832306
9,Num Of Prev Attempts,1145,1145,41.818846,1.000000
10,Code Presentation,1124,1124,41.051863,1.000000
11,Module Presentation Length,1104,1104,40.321402,1.000000
12,Studied Credits,1076,1076,39.298758,1.000000
13,Highest Education,1019,1019,37.216947,1.000000
14,Date Registration,1016,1016,37.107378,1.000000
15,Region,999,999,36.486486,1.000000
16,Imd Band,992,992,36.230825,1.000000
17,Code Module,992,992,36.230825,1.000000
18,Age Band,966,966,35.281227,1.000000
19,Gender,942,942,34.404675,1.000000
20,Disability,921,921,33.637692,1.000000
21,Assessment: Exam,490,490,17.896275,1.000000
22,VLE Clicks: dataplus,273,182,6.647188,1.500000
23,VLE Clicks: oucollaborate,270,170,6.208912,1.588235
24,VLE Clicks: externalquiz,234,136,4.967129,1.720588
25,VLE Clicks: page,211,171,6.245435,1.233918
26,VLE Clicks: ouwiki,125,99,3.615778,1.262626
27,VLE Clicks: dualpane,101,74,2.702703,1.364865
28,VLE Clicks: glossary,72,63,2.300950,1.142857
29,VLE Clicks: folder,69,57,2.081812,1.210526
30,VLE Clicks: questionnaire,26,24,0.876552,1.083333
31,VLE Clicks: ouelluminate,25,21,0.766983,1.190476
32,VLE Clicks: htmlactivity,6,3,0.109569,2.000000

--- Top-20 Feature Counts for: EPSILON-GREEDY (SHAP) ON OULAD_AGGREGATED ---
Based on 2738 common bags.

,Feature Type,Total Count in Top-20,Present in X Bags,Bag Presence %,Avg Count When Present
0,Assessment: TMA,9719,2415,88.203068,4.024431
1,Assessment: CMA,5043,1424,52.008766,3.541433
2,VLE Clicks: homepage,2683,2683,97.991234,1.000000
3,VLE Clicks: subpage,2619,2619,95.653762,1.000000
4,VLE Clicks: resource,2591,2591,94.631118,1.000000
5,VLE Clicks: oucontent,2500,2500,91.307524,1.000000
6,VLE Clicks: forumng,2470,2470,90.211833,1.000000
7,Code Presentation,2323,2323,84.842951,1.000000
8,VLE Clicks: url,2259,2259,82.505478,1.000000
9,Highest Education,2126,2126,77.647918,1.000000
10,Imd Band,2112,2112,77.136596,1.000000
11,Gender,1913,1913,69.868517,1.000000
12,VLE Clicks: quiz,1874,1874,68.444120,1.000000
13,Module Presentation Length,1737,1737,63.440467,1.000000
14,Disability,1586,1586,57.925493,1.000000
15,Studied Credits,1045,1045,38.166545,1.000000
16,VLE Clicks: ouwiki,1012,1012,36.961286,1.000000
17,VLE Clicks: oucollaborate,995,995,36.340394,1.000000
18,Age Band,885,885,32.322863,1.000000
19,Date Registration,848,848,30.971512,1.000000
20,VLE Clicks: page,794,794,28.999270,1.000000
21,Num Of Prev Attempts,676,676,24.689554,1.000000
22,Region,652,652,23.813002,1.000000
23,VLE Clicks: glossary,539,539,19.685902,1.000000
24,Assessment: Exam,500,500,18.261505,1.000000
25,VLE Clicks: externalquiz,437,437,15.960555,1.000000
26,VLE Clicks: questionnaire,433,433,15.814463,1.000000
27,Code Module,414,414,15.120526,1.000000
28,VLE Clicks: ouelluminate,232,232,8.473338,1.000000
29,VLE Clicks: folder,191,191,6.975895,1.000000
30,VLE Clicks: dataplus,143,143,5.222790,1.000000
31,VLE Clicks: dualpane,125,125,4.565376,1.000000
32,VLE Clicks: htmlactivity,106,106,3.871439,1.000000
33,VLE Clicks: sharedsubpage,12,12,0.438276,1.000000

--- Top-20 Feature Counts for: LINEAR ATTENTION ON OULAD_FULL ---
Based on 2738 common bags.

,Feature Type,Total Count in Top-20,Present in X Bags,Bag Presence %,Avg Count When Present
0,VLE Clicks: homepage,15695,2612,95.398101,6.008806
1,Assessment: TMA,7325,2275,83.089847,3.219780
2,VLE Clicks: forumng,6599,1952,71.292915,3.380635
3,Assessment: CMA,6227,1405,51.314828,4.432028
4,VLE Clicks: oucontent,3953,1408,51.424397,2.807528
5,VLE Clicks: subpage,1782,984,35.938641,1.810976
6,VLE Clicks: resource,1572,935,34.149014,1.681283
7,VLE Clicks: quiz,913,585,21.365961,1.560684
8,Code Module,676,676,24.689554,1.000000
9,Code Presentation,665,665,24.287801,1.000000
10,Gender,657,657,23.995617,1.000000
11,Region,644,644,23.520818,1.000000
12,Imd Band,628,628,22.936450,1.000000
13,Age Band,615,615,22.461651,1.000000
14,Disability,604,604,22.059898,1.000000
15,Highest Education,594,594,21.694668,1.000000
16,Module Presentation Length,585,585,21.365961,1.000000
17,Num Of Prev Attempts,573,573,20.927684,1.000000
18,VLE Clicks: externalquiz,568,259,9.459459,2.193050
19,Studied Credits,560,560,20.452885,1.000000
20,Date Registration,543,543,19.831994,1.000000
21,Assessment: Exam,506,506,18.480643,1.000000
22,VLE Clicks: url,355,292,10.664719,1.215753
23,VLE Clicks: dataplus,322,199,7.268079,1.618090
24,VLE Clicks: oucollaborate,292,185,6.756757,1.578378
25,VLE Clicks: folder,146,100,3.652301,1.460000
26,VLE Clicks: glossary,124,99,3.615778,1.252525
27,VLE Clicks: page,117,93,3.396640,1.258065
28,VLE Clicks: ouwiki,105,81,2.958364,1.296296
29,VLE Clicks: dualpane,81,65,2.373996,1.246154
30,VLE Clicks: ouelluminate,27,21,0.766983,1.285714
31,VLE Clicks: questionnaire,16,16,0.584368,1.000000
32,VLE Clicks: htmlactivity,6,5,0.182615,1.200000

--- Top-20 Feature Counts for: GATED ATTENTION ON OULAD_FULL ---
Based on 2738 common bags.

,Feature Type,Total Count in Top-20,Present in X Bags,Bag Presence %,Avg Count When Present
0,VLE Clicks: homepage,16998,2623,95.799854,6.480366
1,VLE Clicks: subpage,6904,2004,73.192111,3.445110
2,VLE Clicks: oucontent,6796,1860,67.932798,3.653763
3,VLE Clicks: forumng,5623,1799,65.704894,3.125625
4,VLE Clicks: resource,3682,1675,61.176041,2.198209
5,VLE Clicks: quiz,2396,1184,43.243243,2.023649
6,VLE Clicks: url,1684,886,32.359386,1.900677
7,Code Module,795,795,29.035793,1.000000
8,Code Presentation,771,771,28.159240,1.000000
9,Gender,753,753,27.501826,1.000000
10,Region,735,735,26.844412,1.000000
11,Imd Band,716,716,26.150475,1.000000
12,Age Band,696,696,25.420015,1.000000
13,Disability,679,679,24.799123,1.000000
14,Highest Education,657,657,23.995617,1.000000
15,Module Presentation Length,640,640,23.374726,1.000000
16,Num Of Prev Attempts,620,620,22.644266,1.000000
17,Studied Credits,606,606,22.132944,1.000000
18,Date Registration,590,590,21.548576,1.000000
19,VLE Clicks: externalquiz,350,191,6.975895,1.832461
20,VLE Clicks: oucollaborate,243,177,6.464573,1.372881
21,Assessment: TMA,237,174,6.355004,1.362069
22,VLE Clicks: page,184,152,5.551497,1.210526
23,VLE Clicks: ouwiki,175,146,5.332359,1.198630
24,VLE Clicks: glossary,141,109,3.981008,1.293578
25,VLE Clicks: folder,84,65,2.373996,1.292308
26,VLE Clicks: questionnaire,72,63,2.300950,1.142857
27,VLE Clicks: dataplus,69,60,2.191381,1.150000
28,VLE Clicks: dualpane,69,57,2.081812,1.210526
29,Assessment: CMA,60,54,1.972243,1.111111
30,VLE Clicks: ouelluminate,44,36,1.314828,1.222222
31,VLE Clicks: htmlactivity,5,5,0.182615,1.000000
32,VLE Clicks: sharedsubpage,1,1,0.036523,1.000000

--- Top-20 Feature Counts for: MULTI-HEAD ATTENTION ON OULAD_FULL ---
Based on 2738 common bags.

,Feature Type,Total Count in Top-20,Present in X Bags,Bag Presence %,Avg Count When Present
0,VLE Clicks: homepage,9263,1527,55.770636,6.066143
1,Assessment: TMA,6234,1943,70.964207,3.208441
2,VLE Clicks: forumng,5773,1608,58.728999,3.590174
3,Assessment: CMA,4851,1208,44.119795,4.015728
4,VLE Clicks: oucontent,2232,728,26.588751,3.065934
5,Code Module,1871,1871,68.334551,1.000000
6,Code Presentation,1867,1867,68.188459,1.000000
7,Gender,1861,1861,67.969321,1.000000
8,Region,1851,1851,67.604091,1.000000
9,Imd Band,1844,1844,67.348430,1.000000
10,Age Band,1839,1839,67.165814,1.000000
11,Disability,1826,1826,66.691015,1.000000
12,Highest Education,1818,1818,66.398831,1.000000
13,Module Presentation Length,1687,1687,61.614317,1.000000
14,Num Of Prev Attempts,1610,1610,58.802045,1.000000
15,Studied Credits,1533,1533,55.989774,1.000000
16,Date Registration,1423,1423,51.972243,1.000000
17,VLE Clicks: subpage,1013,543,19.831994,1.865562
18,VLE Clicks: resource,851,506,18.480643,1.681818
19,VLE Clicks: externalquiz,739,346,12.636961,2.135838
20,VLE Clicks: quiz,538,324,11.833455,1.660494
21,Assessment: Exam,465,465,16.983199,1.000000
22,VLE Clicks: url,214,170,6.208912,1.258824
23,VLE Clicks: dualpane,181,108,3.944485,1.675926
24,VLE Clicks: dataplus,165,103,3.761870,1.601942
25,VLE Clicks: oucollaborate,158,92,3.360117,1.717391
26,VLE Clicks: glossary,114,89,3.250548,1.280899
27,VLE Clicks: folder,103,66,2.410519,1.560606
28,VLE Clicks: page,73,58,2.118335,1.258621
29,VLE Clicks: ouwiki,44,37,1.351351,1.189189
30,VLE Clicks: ouelluminate,16,11,0.401753,1.454545
31,VLE Clicks: questionnaire,10,10,0.365230,1.000000
32,VLE Clicks: htmlactivity,8,4,0.146092,2.000000

--- Top-20 Feature Counts for: LINEAR ATTENTION ON OULAD_AGGREGATED ---
Based on 2738 common bags.

,Feature Type,Total Count in Top-20,Present in X Bags,Bag Presence %,Avg Count When Present
0,Assessment: TMA,9755,2415,88.203068,4.039337
1,Assessment: CMA,4829,1409,51.460920,3.427253
2,VLE Clicks: homepage,2683,2683,97.991234,1.000000
3,VLE Clicks: subpage,2615,2615,95.507670,1.000000
4,VLE Clicks: resource,2585,2585,94.411980,1.000000
5,VLE Clicks: oucontent,2505,2505,91.490139,1.000000
6,VLE Clicks: forumng,2480,2480,90.577064,1.000000
7,Code Module,2357,2357,86.084733,1.000000
8,Imd Band,2287,2287,83.528123,1.000000
9,VLE Clicks: url,2172,2172,79.327977,1.000000
10,Highest Education,2029,2029,74.105186,1.000000
11,Code Presentation,1975,1975,72.132944,1.000000
12,VLE Clicks: quiz,1873,1873,68.407597,1.000000
13,Region,1460,1460,53.323594,1.000000
14,Gender,1208,1208,44.119795,1.000000
15,Module Presentation Length,1135,1135,41.453616,1.000000
16,Date Registration,1126,1126,41.124909,1.000000
17,VLE Clicks: oucollaborate,1043,1043,38.093499,1.000000
18,VLE Clicks: ouwiki,992,992,36.230825,1.000000
19,Studied Credits,953,953,34.806428,1.000000
20,VLE Clicks: page,715,715,26.113952,1.000000
21,Age Band,622,622,22.717312,1.000000
22,VLE Clicks: glossary,583,583,21.292915,1.000000
23,Num Of Prev Attempts,539,539,19.685902,1.000000
24,Assessment: Exam,506,506,18.480643,1.000000
25,Disability,502,502,18.334551,1.000000
26,VLE Clicks: externalquiz,475,475,17.348430,1.000000
27,VLE Clicks: dualpane,374,374,13.659606,1.000000
28,VLE Clicks: questionnaire,369,369,13.476991,1.000000
29,VLE Clicks: dataplus,272,272,9.934259,1.000000
30,VLE Clicks: ouelluminate,228,228,8.327246,1.000000
31,VLE Clicks: folder,191,191,6.975895,1.000000
32,VLE Clicks: htmlactivity,149,149,5.441928,1.000000
33,VLE Clicks: sharedsubpage,7,7,0.255661,1.000000

--- Top-20 Feature Counts for: GATED ATTENTION ON OULAD_AGGREGATED ---
Based on 2738 common bags.

,Feature Type,Total Count in Top-20,Present in X Bags,Bag Presence %,Avg Count When Present
0,Assessment: CMA,5313,1434,52.373996,3.705021
1,Assessment: TMA,3972,1615,58.984660,2.459443
2,Highest Education,2738,2738,100.000000,1.000000
3,Imd Band,2728,2728,99.634770,1.000000
4,VLE Clicks: homepage,2683,2683,97.991234,1.000000
5,VLE Clicks: subpage,2619,2619,95.653762,1.000000
6,Code Module,2609,2609,95.288532,1.000000
7,VLE Clicks: resource,2591,2591,94.631118,1.000000
8,VLE Clicks: oucontent,2507,2507,91.563185,1.000000
9,Date Registration,2489,2489,90.905771,1.000000
10,VLE Clicks: forumng,2480,2480,90.577064,1.000000
11,VLE Clicks: url,2242,2242,81.884587,1.000000
12,Gender,2183,2183,79.729730,1.000000
13,Module Presentation Length,2019,2019,73.739956,1.000000
14,VLE Clicks: quiz,1874,1874,68.444120,1.000000
15,Age Band,1530,1530,55.880205,1.000000
16,Code Presentation,1517,1517,55.405405,1.000000
17,Disability,1215,1215,44.375457,1.000000
18,VLE Clicks: oucollaborate,1065,1065,38.897005,1.000000
19,VLE Clicks: ouwiki,1045,1045,38.166545,1.000000
20,Num Of Prev Attempts,920,920,33.601169,1.000000
21,Region,861,861,31.446311,1.000000
22,VLE Clicks: page,833,833,30.423667,1.000000
23,Studied Credits,771,771,28.159240,1.000000
24,VLE Clicks: glossary,591,591,21.585099,1.000000
25,VLE Clicks: externalquiz,475,475,17.348430,1.000000
26,VLE Clicks: questionnaire,444,444,16.216216,1.000000
27,VLE Clicks: dualpane,374,374,13.659606,1.000000
28,VLE Clicks: dataplus,272,272,9.934259,1.000000
29,VLE Clicks: ouelluminate,243,243,8.875091,1.000000
30,VLE Clicks: folder,191,191,6.975895,1.000000
31,VLE Clicks: htmlactivity,186,186,6.793280,1.000000
32,VLE Clicks: sharedsubpage,13,13,0.474799,1.000000
33,Assessment: Exam,1,1,0.036523,1.000000

--- Top-20 Feature Counts for: MULTI-HEAD ATTENTION ON OULAD_AGGREGATED ---
Based on 2738 common bags.

,Feature Type,Total Count in Top-20,Present in X Bags,Bag Presence %,Avg Count When Present
0,Assessment: TMA,3158,1362,49.744339,2.318649
1,Assessment: CMA,2917,1066,38.933528,2.736398
2,Age Band,2668,2668,97.443389,1.000000
3,Studied Credits,2660,2660,97.151205,1.000000
4,Disability,2646,2646,96.639883,1.000000
5,Num Of Prev Attempts,2608,2608,95.252009,1.000000
6,Region,2553,2553,93.243243,1.000000
7,Date Registration,2526,2526,92.257122,1.000000
8,Gender,2519,2519,92.001461,1.000000
9,Highest Education,2468,2468,90.138787,1.000000
10,Code Module,2467,2467,90.102264,1.000000
11,Module Presentation Length,2444,2444,89.262235,1.000000
12,VLE Clicks: homepage,2348,2348,85.756026,1.000000
13,Imd Band,2346,2346,85.682980,1.000000
14,VLE Clicks: forumng,2214,2214,80.861943,1.000000
15,VLE Clicks: oucontent,2146,2146,78.378378,1.000000
16,VLE Clicks: resource,1781,1781,65.047480,1.000000
17,Code Presentation,1772,1772,64.718773,1.000000
18,VLE Clicks: subpage,1675,1675,61.176041,1.000000
19,VLE Clicks: url,1408,1408,51.424397,1.000000
20,VLE Clicks: quiz,1406,1406,51.351351,1.000000
21,VLE Clicks: oucollaborate,927,927,33.856830,1.000000
22,VLE Clicks: ouwiki,777,777,28.378378,1.000000
23,VLE Clicks: page,545,545,19.905040,1.000000
24,VLE Clicks: glossary,537,537,19.612856,1.000000
25,VLE Clicks: externalquiz,434,434,15.850986,1.000000
26,Assessment: Exam,327,327,11.943024,1.000000
27,VLE Clicks: dualpane,319,319,11.650840,1.000000
28,VLE Clicks: questionnaire,273,273,9.970782,1.000000
29,VLE Clicks: dataplus,248,248,9.057706,1.000000
30,VLE Clicks: ouelluminate,182,182,6.647188,1.000000
31,VLE Clicks: htmlactivity,169,169,6.172389,1.000000
32,VLE Clicks: folder,118,118,4.309715,1.000000
33,VLE Clicks: sharedsubpage,8,8,0.292184,1.000000

In [11]:
# Step 7: Reliance on Demographics

reliance_results = []
for model_name in all_dfs.keys():
    if "oulad_full" in model_name:
        dataset_name = "oulad_full"
    elif "oulad_aggregated" in model_name:
        dataset_name = "oulad_aggregated"
    else:
        continue

    total_possible_instances = len(common_bags_per_dataset[dataset_name]) * TOP_K_FOR_COUNTS
    demographic_instance_count = sum(
        all_counts[model_name].get(label, 0) for label in DEMOGRAPHIC_LABELS
    )
    if total_possible_instances > 0:
        reliance_percentage = (demographic_instance_count / total_possible_instances) * 100
    else:
        reliance_percentage = 0
        
    reliance_results.append({
        "Model": model_name,
        "Reliance on Demographics (%)": f"{reliance_percentage:.1f}%"
    })

reliance_df = pd.DataFrame(reliance_results)

display(reliance_df.sort_values(by="Model").reset_index(drop=True))

--- Reliance on Demographics ---

                                       Model Reliance on Demographics (%)
0  Epsilon-Greedy (SHAP) on oulad_aggregated                        13.1%
1        Epsilon-Greedy (SHAP) on oulad_full                         8.8%
2        Gated Attention on oulad_aggregated                        15.6%
3              Gated Attention on oulad_full                         6.5%
4       Linear Attention on oulad_aggregated                        11.1%
5             Linear Attention on oulad_full                         5.7%
6   Multi-Head Attention on oulad_aggregated                        23.3%
7         Multi-Head Attention on oulad_full                        16.8%

In [12]:
# Step 8: Sparsity Metrics
sparsity_results = []
for model_name in all_dfs.keys():
    
    if "oulad_full" in model_name:
        dataset_name = "oulad_full"
    elif "oulad_aggregated" in model_name:
        dataset_name = "oulad_aggregated"
    else:
        continue
        
    total_bags_for_dataset = len(common_bags_per_dataset[dataset_name])
    sparsity_results.append({
        "Model": model_name,
        "Gini Coefficient": calculate_gini(all_counts[model_name]),
        "HHI Score": calculate_hhi(all_counts[model_name], total_bags_for_dataset),
    })

sparsity_df = pd.DataFrame(sparsity_results)

display(sparsity_df.sort_values(by="Model").reset_index(drop=True))

--- Sparsity Metrics ---

                                       Model  Gini Coefficient  HHI Score
0  Epsilon-Greedy (SHAP) on oulad_aggregated          0.503193   0.064211
1        Epsilon-Greedy (SHAP) on oulad_full          0.608344   0.088632
2        Gated Attention on oulad_aggregated          0.422240   0.044976
3              Gated Attention on oulad_full          0.730198   0.147605
4       Linear Attention on oulad_aggregated          0.493194   0.063529
5             Linear Attention on oulad_full          0.702741   0.136693
6   Multi-Head Attention on oulad_aggregated          0.364944   0.040062
7         Multi-Head Attention on oulad_full          0.576559   0.075561

In [13]:
# Step 9: Consistency Metrics (Split-Half Method) 

consistency_results = []
np.random.seed(REPRODUCIBILITY_SEED)

for dataset_name, common_bags in common_bags_per_dataset.items():
    
    print(f"\n- Splitting bags for dataset: {dataset_name}")
    
    shuffled_bags = np.array(common_bags)
    np.random.shuffle(shuffled_bags)
    split_point = len(shuffled_bags) // 2
    bags_a, bags_b = shuffled_bags[:split_point], shuffled_bags[split_point:]
    
    correct_map_for_model = bag_to_labels_maps[dataset_name]

    for model_name, df in all_dfs.items():
        if dataset_name in model_name:
            print(f"  -> Calculating for model: {model_name}...")
            
            base_model_name = model_name.replace(f" on {dataset_name}", "")
            score_col = DATASET_CONFIGS[dataset_name]['models'][base_model_name]['score_column']
            
            counts_a = get_counts_for_split(bags_a, df, score_col, correct_map_for_model)
            counts_b = get_counts_for_split(bags_b, df, score_col, correct_map_for_model)
            
            policy_df = pd.DataFrame({'split_A': counts_a, 'split_B': counts_b}).fillna(0)
            spearman_corr, _ = spearmanr(policy_df['split_A'], policy_df['split_B'])
            
            top5_a = set(policy_df.nlargest(5, 'split_A').index)
            top5_b = set(policy_df.nlargest(5, 'split_B').index)

            print(f"    - Top 5 (Split A): {sorted(list(top5_a))}")
            print(f"    - Top 5 (Split B): {sorted(list(top5_b))}")
            
            jaccard_k5_score = len(top5_a.intersection(top5_b)) / len(top5_a.union(top5_b)) if top5_a and top5_b else 0.0

            result_row = {"Model": model_name, "Spearman's Rank (Stability)": spearman_corr, "Jaccard (K=5)": jaccard_k5_score}
            consistency_results.append(result_row)

consistency_df = pd.DataFrame(consistency_results)
display(consistency_df.sort_values(by="Model").reset_index(drop=True))

--- Calculating Consistency Metrics ---

- Splitting bags for dataset: oulad_full
  -> Calculating for model: Epsilon-Greedy (SHAP) on oulad_full...

    - Top 5 (Split A): ['Assessment: TMA', 'VLE Clicks: forumng', 'VLE Clicks: homepage', 'VLE Clicks: oucontent', 'VLE Clicks: subpage']
    - Top 5 (Split B): ['Assessment: TMA', 'VLE Clicks: forumng', 'VLE Clicks: homepage', 'VLE Clicks: oucontent', 'VLE Clicks: subpage']
  -> Calculating for model: Linear Attention on oulad_full...
    - Top 5 (Split A): ['Assessment: CMA', 'Assessment: TMA', 'VLE Clicks: forumng', 'VLE Clicks: homepage', 'VLE Clicks: oucontent']
    - Top 5 (Split B): ['Assessment: CMA', 'Assessment: TMA', 'VLE Clicks: forumng', 'VLE Clicks: homepage', 'VLE Clicks: oucontent']
  -> Calculating for model: Gated Attention on oulad_full...
    - Top 5 (Split A): ['VLE Clicks: forumng', 'VLE Clicks: homepage', 'VLE Clicks: oucontent', 'VLE Clicks: resource', 'VLE Clicks: subpage']
    - Top 5 (Split B): ['VLE Clicks: forumng', 'VLE Clicks: homepage', 'VLE Clicks: oucontent', 'VLE Clicks: resource', 'VLE Clicks: subpage']
  -> Calculating for model: Multi-Head Attention on oulad_full...
    - Top 5 (Split A): ['Assessment: CMA', 'Assessment: TMA', 'VLE Clicks: forumng', 'VLE Clicks: homepage', 'VLE Clicks: oucontent']
    - Top 5 (Split B): ['Assessment: CMA', 'Assessment: TMA', 'VLE Clicks: forumng', 'VLE Clicks: homepage', 'VLE Clicks: oucontent']

- Splitting bags for dataset: oulad_aggregated
  -> Calculating for model: Epsilon-Greedy (SHAP) on oulad_aggregated...
    - Top 5 (Split A): ['Assessment: CMA', 'Assessment: TMA', 'VLE Clicks: homepage', 'VLE Clicks: resource', 'VLE Clicks: subpage']
    - Top 5 (Split B): ['Assessment: CMA', 'Assessment: TMA', 'VLE Clicks: homepage', 'VLE Clicks: resource', 'VLE Clicks: subpage']
  -> Calculating for model: Linear Attention on oulad_aggregated...
    - Top 5 (Split A): ['Assessment: CMA', 'Assessment: TMA', 'VLE Clicks: homepage', 'VLE Clicks: resource', 'VLE Clicks: subpage']
    - Top 5 (Split B): ['Assessment: CMA', 'Assessment: TMA', 'VLE Clicks: homepage', 'VLE Clicks: resource', 'VLE Clicks: subpage']
  -> Calculating for model: Gated Attention on oulad_aggregated...
    - Top 5 (Split A): ['Assessment: CMA', 'Assessment: TMA', 'Highest Education', 'Imd Band', 'VLE Clicks: homepage']
    - Top 5 (Split B): ['Assessment: CMA', 'Assessment: TMA', 'Highest Education', 'Imd Band', 'VLE Clicks: homepage']
  -> Calculating for model: Multi-Head Attention on oulad_aggregated...
    - Top 5 (Split A): ['Age Band', 'Assessment: CMA', 'Assessment: TMA', 'Disability', 'Studied Credits']
    - Top 5 (Split B): ['Age Band', 'Assessment: CMA', 'Assessment: TMA', 'Disability', 'Studied Credits']

--- Final Consistency Metrics ---

,Model,Spearman's Rank (Stability),Jaccard (K=5)
0,Epsilon-Greedy (SHAP) on oulad_aggregated,0.997402,1.0
1,Epsilon-Greedy (SHAP) on oulad_full,0.997242,1.0
2,Gated Attention on oulad_aggregated,0.999389,1.0
3,Gated Attention on oulad_full,0.994234,1.0
4,Linear Attention on oulad_aggregated,0.997861,1.0
5,Linear Attention on oulad_full,0.986379,1.0
6,Multi-Head Attention on oulad_aggregated,0.997555,1.0
7,Multi-Head Attention on oulad_full,0.998663,1.0

In [14]:
# Step 10: save results to csv's
SPARSITY_FILE = os.path.join(OUTPUT_DIR, 'master_sparsity_metrics.csv')
CONSISTENCY_FILE = os.path.join(OUTPUT_DIR, 'master_consistency_metrics.csv')
DEMOGRAPHICS_FILE = os.path.join(OUTPUT_DIR, 'master_demographics_metrics.csv')

sparsity_df['seed'] = SEED_TO_ANALYZE
sparsity_df['pooling_method'] = POOLING_METHOD_TO_ANALYZE

consistency_df['seed'] = SEED_TO_ANALYZE
consistency_df['pooling_method'] = POOLING_METHOD_TO_ANALYZE

reliance_df['seed'] = SEED_TO_ANALYZE
reliance_df['pooling_method'] = POOLING_METHOD_TO_ANALYZE

try:
    append_to_csv(sparsity_df, SPARSITY_FILE)
    append_to_csv(consistency_df, CONSISTENCY_FILE)
    append_to_csv(reliance_df, DEMOGRAPHICS_FILE)
except NameError as e:
    print(f"ERROR: A results DataFrame is not defined. Please ensure the notebook has run successfully. Details: {e}")

Appended new results to: ../results/master_sparsity_metrics.csv
Appended new results to: ../results/master_consistency_metrics.csv
Appended new results to: ../results/master_demographics_metrics.csv
\n--- All results for this run have been saved successfully. ---